package projeto;

import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class Cadastrar extends javax.swing.JInternalFrame {
    //Declaração dos ArrayLists
    ArrayList<Recurso> recursos = new ArrayList();
    ArrayList<Autor> autores = new ArrayList();
    ArrayList<PalavraChave> palavrasChaves = new ArrayList();
    ArrayList<Historico> historico = new ArrayList();
    ArrayList<Usuario> usuarios = new ArrayList();
    
    public Cadastrar() {
        initComponents();
        //Chamando o método de preenchimento automático.
        teste();
        
        //Adicionando o "login" do Arraylist "usuarios" na ComboBox "cbHistoricoUsuarios".
        for(int i=0;i<usuarios.size();i++){
            cbHistoricoUsuarios.addItem(usuarios.get(i).getNome());
        }
    }
    
    //Método de preenchimento automático
    public void teste(){
        //Adicionando os valores ao ArrayList "usuarios".
        usuarios.add(new Usuario("usuario1", "123", "Usuario1", "usuario1@gmail.com"));
        usuarios.add(new Usuario("usuario2", "123", "Usuario2", "usuario2@gmail.com"));
        usuarios.add(new Usuario("usuario3", "123", "Usuario3", "usuario3@gmail.com"));
        
        //Instanciando o objeto "autores[]" e armazenando os valores
        Autor autores[] = {new Autor("GG", "usuario1", "usuario1@gmail.com")};
        PalavraChave palavraChaves[] = {new PalavraChave("porta", "door")};
        Historico historico[] = {new Historico(new Usuario("usuario3", "123", "Usuario3", "usuario3@gmail.com"), "16/05/2019", "Livro para estudado")};
        
        //Adicionando os valores ao ArrayList "recursos".
        recursos.add(new Recurso(1, "ABC", "Médio", "txt", "Matemática", "16/05/2019", autores, palavraChaves, historico));
        DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
        modelo.addRow(new String[]{"16/05/2019", Integer.toString(1),"ABC", "Médio", "txt", "Matemática"});
        //-------------------------------------------------------------------------------------------------------------------------------------
               
    }
    
    //Método de Centralização dos JInternalFrames.
    public void setPosicao(){
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogAutores = new javax.swing.JDialog();
        btnAutorCadastrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAutorNome = new javax.swing.JTextField();
        txtAutorEmail = new javax.swing.JTextField();
        txtAutorEsp = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jDialogUsuario = new javax.swing.JDialog();
        btnUsuCadastrar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtUsuNome = new javax.swing.JTextField();
        txtUsuEmail = new javax.swing.JTextField();
        txtUsuLogin = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtUsuSenha = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jDialogHistorico = new javax.swing.JDialog();
        btnHistoricoCadastrar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtHistoricoDtAtualizacao = new javax.swing.JTextField();
        txtHistoricoDesc = new javax.swing.JTextField();
        cbHistoricoUsuarios = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jDialogPalavraChave = new javax.swing.JDialog();
        btnPlvChaveCadastrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPlvChavePort = new javax.swing.JTextField();
        txtPlvChaveIng = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDataCriacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbNivelEnsino = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtDiscp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnAutores = new javax.swing.JButton();
        btnPalavrasChaves = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        btnCadRecurso = new javax.swing.JButton();
        btnCadUsuario = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtFormato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        jDialogAutores.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogAutores.setBackground(new java.awt.Color(255, 255, 255));
        jDialogAutores.setBounds(new java.awt.Rectangle(0, 0, 400, 135));
        jDialogAutores.setResizable(false);
        jDialogAutores.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAutorCadastrar.setBackground(new java.awt.Color(91, 120, 158));
        btnAutorCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAutorCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnAutorCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/add.png"))); // NOI18N
        btnAutorCadastrar.setText("Cadastrar");
        btnAutorCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 3));
        btnAutorCadastrar.setContentAreaFilled(false);
        btnAutorCadastrar.setOpaque(true);
        btnAutorCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorCadastrarActionPerformed(evt);
            }
        });
        jDialogAutores.getContentPane().add(btnAutorCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 214, 31));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nome:");
        jDialogAutores.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, -1, 26));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("E-mail:");
        jDialogAutores.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 149, -1, 26));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Especialidade:");
        jDialogAutores.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 207, -1, 26));
        jDialogAutores.getContentPane().add(txtAutorNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 380, -1));
        jDialogAutores.getContentPane().add(txtAutorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 380, -1));
        jDialogAutores.getContentPane().add(txtAutorEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 239, 380, -1));

        jLabel20.setBackground(new java.awt.Color(91, 120, 158));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Autores");
        jLabel20.setMaximumSize(new java.awt.Dimension(106, 29));
        jLabel20.setMinimumSize(new java.awt.Dimension(106, 29));
        jLabel20.setOpaque(true);
        jDialogAutores.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 78));

        jDialogUsuario.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogUsuario.setBounds(new java.awt.Rectangle(0, 0, 400, 135));
        jDialogUsuario.setResizable(false);

        btnUsuCadastrar.setBackground(new java.awt.Color(91, 120, 158));
        btnUsuCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUsuCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/add.png"))); // NOI18N
        btnUsuCadastrar.setText("Cadastrar");
        btnUsuCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 3));
        btnUsuCadastrar.setContentAreaFilled(false);
        btnUsuCadastrar.setOpaque(true);
        btnUsuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuCadastrarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Nome:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("E-mail:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Login:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Senha:");

        jLabel21.setBackground(new java.awt.Color(91, 120, 158));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Usuário");
        jLabel21.setMaximumSize(new java.awt.Dimension(106, 29));
        jLabel21.setMinimumSize(new java.awt.Dimension(106, 29));
        jLabel21.setOpaque(true);
        jLabel21.setPreferredSize(new java.awt.Dimension(92, 29));

        javax.swing.GroupLayout jDialogUsuarioLayout = new javax.swing.GroupLayout(jDialogUsuario.getContentPane());
        jDialogUsuario.getContentPane().setLayout(jDialogUsuarioLayout);
        jDialogUsuarioLayout.setHorizontalGroup(
            jDialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDialogUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuEmail)
                    .addComponent(txtUsuNome)
                    .addGroup(jDialogUsuarioLayout.createSequentialGroup()
                        .addGroup(jDialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogUsuarioLayout.createSequentialGroup()
                        .addGroup(jDialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(txtUsuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jDialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))))
                .addContainerGap())
            .addGroup(jDialogUsuarioLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(btnUsuCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialogUsuarioLayout.setVerticalGroup(
            jDialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogUsuarioLayout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnUsuCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jDialogHistorico.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogHistorico.setBounds(new java.awt.Rectangle(0, 0, 400, 135));
        jDialogHistorico.setResizable(false);

        btnHistoricoCadastrar.setBackground(new java.awt.Color(91, 120, 158));
        btnHistoricoCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistoricoCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnHistoricoCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/add.png"))); // NOI18N
        btnHistoricoCadastrar.setText("Cadastrar");
        btnHistoricoCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 3));
        btnHistoricoCadastrar.setContentAreaFilled(false);
        btnHistoricoCadastrar.setOpaque(true);
        btnHistoricoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoCadastrarActionPerformed(evt);
            }
        });

        jLabel13.setText("Data de atualização:");

        jLabel14.setText("Descrição:");

        jLabel19.setText("Responsavel:");

        jLabel22.setBackground(new java.awt.Color(91, 120, 158));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Histórico");
        jLabel22.setOpaque(true);

        javax.swing.GroupLayout jDialogHistoricoLayout = new javax.swing.GroupLayout(jDialogHistorico.getContentPane());
        jDialogHistorico.getContentPane().setLayout(jDialogHistoricoLayout);
        jDialogHistoricoLayout.setHorizontalGroup(
            jDialogHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogHistoricoLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(btnHistoricoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
            .addGroup(jDialogHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHistoricoDesc)
                    .addGroup(jDialogHistoricoLayout.createSequentialGroup()
                        .addGroup(jDialogHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDialogHistoricoLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(cbHistoricoUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jDialogHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHistoricoDtAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogHistoricoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addGap(85, 85, 85))))
                    .addGroup(jDialogHistoricoLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialogHistoricoLayout.setVerticalGroup(
            jDialogHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogHistoricoLayout.createSequentialGroup()
                .addGroup(jDialogHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogHistoricoLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(cbHistoricoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialogHistoricoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(txtHistoricoDtAtualizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtHistoricoDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnHistoricoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jDialogPalavraChave.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogPalavraChave.setBounds(new java.awt.Rectangle(0, 0, 400, 120));
        jDialogPalavraChave.setResizable(false);

        btnPlvChaveCadastrar.setBackground(new java.awt.Color(91, 120, 158));
        btnPlvChaveCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPlvChaveCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnPlvChaveCadastrar.setText("Cadastrar");
        btnPlvChaveCadastrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 204, 255), 3));
        btnPlvChaveCadastrar.setContentAreaFilled(false);
        btnPlvChaveCadastrar.setOpaque(true);
        btnPlvChaveCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlvChaveCadastrarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Termo em português:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Termo em inglês:");

        jLabel23.setBackground(new java.awt.Color(91, 120, 158));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Palavra Chave");
        jLabel23.setOpaque(true);

        javax.swing.GroupLayout jDialogPalavraChaveLayout = new javax.swing.GroupLayout(jDialogPalavraChave.getContentPane());
        jDialogPalavraChave.getContentPane().setLayout(jDialogPalavraChaveLayout);
        jDialogPalavraChaveLayout.setHorizontalGroup(
            jDialogPalavraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPalavraChaveLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialogPalavraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPlvChavePort, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jDialogPalavraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPlvChaveIng, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addContainerGap())
            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPalavraChaveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPlvChaveCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jDialogPalavraChaveLayout.setVerticalGroup(
            jDialogPalavraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPalavraChaveLayout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialogPalavraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialogPalavraChaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlvChavePort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlvChaveIng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPlvChaveCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setClosable(true);
        setTitle("Cadastrar");
        setFrameIcon(null);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Codigo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Data de criação:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nivel de ensino:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Formato:");

        cbNivelEnsino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Educação Infantil", "Ensino Fundamental", "Ensino Médio" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Disciplina:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Titulo:");

        btnAutores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/group.png"))); // NOI18N
        btnAutores.setText("Autores");
        btnAutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutoresActionPerformed(evt);
            }
        });

        btnPalavrasChaves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/key_add.png"))); // NOI18N
        btnPalavrasChaves.setText("Palavras chaves");
        btnPalavrasChaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalavrasChavesActionPerformed(evt);
            }
        });

        btnHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/application_view_list.png"))); // NOI18N
        btnHistorico.setText("Histórico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        btnCadRecurso.setBackground(new java.awt.Color(91, 120, 158));
        btnCadRecurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadRecurso.setForeground(new java.awt.Color(255, 255, 255));
        btnCadRecurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/table_add.png"))); // NOI18N
        btnCadRecurso.setText("Cadastrar Recurso");
        btnCadRecurso.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        btnCadRecurso.setContentAreaFilled(false);
        btnCadRecurso.setOpaque(true);
        btnCadRecurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadRecursoActionPerformed(evt);
            }
        });

        btnCadUsuario.setBackground(new java.awt.Color(91, 120, 158));
        btnCadUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/user_add.png"))); // NOI18N
        btnCadUsuario.setText("Cadastrar Usuário");
        btnCadUsuario.setActionCommand("b");
        btnCadUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 204, 255), 3, true));
        btnCadUsuario.setContentAreaFilled(false);
        btnCadUsuario.setOpaque(true);
        btnCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadUsuarioActionPerformed(evt);
            }
        });

        tabela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data de criação", "Codigo", "Título", "Nível de ensino", "Formato", "Disciplina"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadRecurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDiscp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPalavrasChaves, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtDataCriacao)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(cbNivelEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtFormato))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNivelEnsino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDiscp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAutores)
                    .addComponent(btnPalavrasChaves)
                    .addComponent(btnHistorico))
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadRecurso, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jLabel8.setBackground(new java.awt.Color(91, 120, 158));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Cadastro");
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutoresActionPerformed
        //Definindo tamanho para o JDialog "jDialogAutores" e exibindo o mesmo centralizado.
        jDialogAutores.setSize(400, 370);
        jDialogAutores.setLocationRelativeTo(null);
        jDialogPalavraChave.setVisible(false);
        jDialogHistorico.setVisible(false);
        jDialogUsuario.setVisible(false);
        jDialogAutores.setVisible(true);
        
    }//GEN-LAST:event_btnAutoresActionPerformed

    private void btnPalavrasChavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalavrasChavesActionPerformed
        //Definindo tamanho para o JDialog "jDialogPalavraChave" e exibindo o mesmo centralizado.
        jDialogPalavraChave.setSize(360, 260);
        jDialogPalavraChave.setLocationRelativeTo(null);
        jDialogAutores.setVisible(false);
        jDialogHistorico.setVisible(false);
        jDialogUsuario.setVisible(false);
        jDialogPalavraChave.setVisible(true);
    }//GEN-LAST:event_btnPalavrasChavesActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        //Definindo tamanho para o JDialog "jDialogHistorico" e exibindo o mesmo centralizado.
        jDialogHistorico.setSize(400, 350);
        jDialogHistorico.setLocationRelativeTo(null);
        jDialogAutores.setVisible(false);
        jDialogPalavraChave.setVisible(false);
        jDialogUsuario.setVisible(false);
        jDialogHistorico.setVisible(true);
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void btnCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadUsuarioActionPerformed
        //Definindo tamanho para o JDialog "jDialogUsuario" e exibindo o mesmo centralizado.
        jDialogUsuario.setSize(410, 400);
        jDialogUsuario.setLocationRelativeTo(null);
        jDialogAutores.setVisible(false);
        jDialogPalavraChave.setVisible(false);
        jDialogHistorico.setVisible(false);
        jDialogUsuario.setVisible(true);
    }//GEN-LAST:event_btnCadUsuarioActionPerformed

    private void btnCadRecursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadRecursoActionPerformed
        //Verificar se há campos que não foram preenchidos
        if(txtCodigo.getText().equals("") || txtTitulo.getText().equals("") || cbNivelEnsino.getSelectedIndex() == 0 || txtFormato.getText().equals("") || txtDiscp.getText().equals("") || txtDataCriacao.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        }else if(autores.isEmpty()){
            JOptionPane.showMessageDialog(this, "Cadastre pelo menos um autor!");
        }else if(palavrasChaves.isEmpty()){
            JOptionPane.showMessageDialog(this, "Cadastre pelo menos uma palavra chave!");
        }else if(historico.isEmpty()){
            JOptionPane.showMessageDialog(this, "Cadastre pelo menos um histórico!");
        }else{
            //Declaração e atribuição dos valores as variáveis por meio do método "Getter".
            String titulo = txtTitulo.getText(), nivelEnsino = cbNivelEnsino.getSelectedItem().toString(),
            formato = txtFormato.getText(), discp = txtDiscp.getText(), dataCriacao = txtDataCriacao.getText();
            int codigo = Integer.parseInt(txtCodigo.getText());
            
            //Instanciando objetos com tamanho referente aos ArrayLists.
            Autor vetAutor[] = new Autor[autores.size()];
            PalavraChave vetPalavraChave[] = new PalavraChave[palavrasChaves.size()];
            Historico vetHistorico[] = new Historico[historico.size()];
            
            //Armazenando os valores nos vetores.
            for(int i=0;i<autores.size();i++){
                vetAutor[i] = autores.get(i);
            }
            for(int i=0;i<palavrasChaves.size();i++){
                vetPalavraChave[i] = palavrasChaves.get(i);
            }
            for(int i=0;i<historico.size();i++){
                vetHistorico[i] = historico.get(i);
            }
            
            //Adicionando os valores no Arraylist "recursos"
            recursos.add(new Recurso(codigo, titulo, nivelEnsino, formato, discp, dataCriacao, vetAutor, vetPalavraChave, vetHistorico));
            
            //Adicionando daods na tabela
            DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
            modelo.addRow(new String[]{dataCriacao, Integer.toString(codigo), titulo, nivelEnsino, formato, discp});
            
            //Limpando os campos
            txtCodigo.setText(""); txtTitulo.setText(""); cbNivelEnsino.setSelectedIndex(0); txtFormato.setText(""); txtDiscp.setText(""); txtDataCriacao.setText("");
            
            //Limpando os ArrayLists
            autores.clear();
            palavrasChaves.clear();
            historico.clear();
        }
    }//GEN-LAST:event_btnCadRecursoActionPerformed

    private void btnAutorCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorCadastrarActionPerformed
        //Verificar se há campos que não foram preenchidos
        if(txtAutorNome.getText().equals("") || txtAutorEmail.getText().equals("") || txtAutorEsp.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        }else{
            //Declaração e atribuição dos valores as variáveis por meio do método "Getter".
            String nome = txtAutorNome.getText(), email = txtAutorEmail.getText(), esp = txtAutorEsp.getText();
            
            //Adicionando os valores no Arraylist "autores"
            autores.add(new Autor(esp, nome, email));
            
            //Limpando os campos
            txtAutorNome.setText(""); txtAutorEmail.setText(""); txtAutorEsp.setText("");
        }
    }//GEN-LAST:event_btnAutorCadastrarActionPerformed

    private void btnUsuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuCadastrarActionPerformed
        //Verificar se há campos que não foram preenchidos
        if(txtUsuNome.getText().equals("") || txtUsuEmail.getText().equals("") || txtUsuLogin.getText().equals("") || txtUsuSenha.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        }else{
            //Declaração e atribuição dos valores as variáveis por meio do método "Getter".
            String nome = txtUsuNome.getText(), email = txtUsuEmail.getText(), login = txtUsuLogin.getText(), senha = txtUsuSenha.getText();
            
            //Adicionando os valores no Arraylist "usuarios" e armazenando a variável "nome" na ComboBox "cbHistoricoUsuarios".
            usuarios.add(new Usuario(login, senha, nome, email));
            cbHistoricoUsuarios.addItem(nome);
            
            //Limpando os campos
            txtUsuNome.setText("");
            txtUsuEmail.setText("");
            txtUsuLogin.setText("");
            txtUsuSenha.setText("");
        }
    }//GEN-LAST:event_btnUsuCadastrarActionPerformed

    private void btnHistoricoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoCadastrarActionPerformed
        //Verificar se há campos que não foram preenchidos
        if(txtHistoricoDtAtualizacao.getText().equals("") || txtHistoricoDesc.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        }else{
            //Declaração e atribuição dos valores as variáveis por meio do método "Getter".
            String dtAtualizacao = txtHistoricoDtAtualizacao.getText(), desc = txtHistoricoDesc.getText();
            int pos = cbHistoricoUsuarios.getSelectedIndex();
            
            //Instanciando objeto e armazenando um o ArrayList na posição "pos".
            Usuario usu = usuarios.get(pos);
            
            //Adicionando os valores no Arraylist "historico"
            historico.add(new Historico(usu, dtAtualizacao, desc));
            
            //Limpando os campos
            txtHistoricoDtAtualizacao.setText("");
            txtHistoricoDesc.setText("");
        }
    }//GEN-LAST:event_btnHistoricoCadastrarActionPerformed

    private void btnPlvChaveCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlvChaveCadastrarActionPerformed
        //Verificar se há campos que não foram preenchidos
        if(txtPlvChavePort.getText().equals("") || txtPlvChaveIng.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        }else{
            //Declaração e atribuição dos valores as variáveis por meio do método "Getter".
            String chavePort = txtPlvChavePort.getText(), chaveIng = txtPlvChaveIng.getText();
            
            //Adicionando os valores no Arraylist "palavrasChave".
            palavrasChaves.add(new PalavraChave(chavePort, chaveIng));
            
            //Limpando os campos
            txtPlvChavePort.setText("");
            txtPlvChaveIng.setText("");
        }
    }//GEN-LAST:event_btnPlvChaveCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutorCadastrar;
    private javax.swing.JButton btnAutores;
    private javax.swing.JButton btnCadRecurso;
    private javax.swing.JButton btnCadUsuario;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnHistoricoCadastrar;
    private javax.swing.JButton btnPalavrasChaves;
    private javax.swing.JButton btnPlvChaveCadastrar;
    private javax.swing.JButton btnUsuCadastrar;
    private javax.swing.JComboBox cbHistoricoUsuarios;
    private javax.swing.JComboBox<String> cbNivelEnsino;
    private javax.swing.JDialog jDialogAutores;
    private javax.swing.JDialog jDialogHistorico;
    private javax.swing.JDialog jDialogPalavraChave;
    private javax.swing.JDialog jDialogUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField txtAutorEmail;
    private javax.swing.JTextField txtAutorEsp;
    private javax.swing.JTextField txtAutorNome;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDataCriacao;
    private javax.swing.JTextField txtDiscp;
    private javax.swing.JTextField txtFormato;
    private javax.swing.JTextField txtHistoricoDesc;
    private javax.swing.JTextField txtHistoricoDtAtualizacao;
    private javax.swing.JTextField txtPlvChaveIng;
    private javax.swing.JTextField txtPlvChavePort;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUsuEmail;
    private javax.swing.JTextField txtUsuLogin;
    private javax.swing.JTextField txtUsuNome;
    private javax.swing.JTextField txtUsuSenha;
    // End of variables declaration//GEN-END:variables
}
