package projeto;

import java.awt.Container;
import javax.swing.JFrame;
import javax.swing.plaf.basic.BasicInternalFrameUI;

public class MenuPrincipal extends javax.swing.JFrame {
    //Instanciando Objetos.
    Cadastrar janelaCadastrar = new Cadastrar();
    Consultar janelaConsultar = new Consultar();
    Desenvolvedores janelaDesenvolvedores = new Desenvolvedores();
    
    
    public MenuPrincipal() {
        //Maximizar JDesktopPane "areaTrabalho".
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents(); 
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuCadastrar = new javax.swing.JMenuItem();
        mnuConsultar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuGrupo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(areaTrabalho, java.awt.BorderLayout.CENTER);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/application_form_edit.png"))); // NOI18N
        jMenu1.setText("Materiais");

        mnuCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ADD, java.awt.event.InputEvent.CTRL_MASK));
        mnuCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/add.png"))); // NOI18N
        mnuCadastrar.setText("Cadastrar");
        mnuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuCadastrar);

        mnuConsultar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/magnifier.png"))); // NOI18N
        mnuConsultar.setText("Consultar");
        mnuConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/information.png"))); // NOI18N
        jMenu2.setText("Sobre");

        mnuGrupo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        mnuGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/Icones/group.png"))); // NOI18N
        mnuGrupo.setText("Desenvolvedores");
        mnuGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGrupoActionPerformed(evt);
            }
        });
        jMenu2.add(mnuGrupo);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastrarActionPerformed
        //Remover Icone do JInternalFrame.
        Container pane = ((BasicInternalFrameUI) janelaCadastrar.getUI()).getNorthPane();
        pane.getComponent(0).setVisible(false);
        
        //Adicionando e exibindo a janela "Cadastrar" centralizada.
        areaTrabalho.add(janelaCadastrar);
        janelaCadastrar.setVisible(true);
        janelaCadastrar.setPosicao();
    }//GEN-LAST:event_mnuCadastrarActionPerformed

    private void mnuConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarActionPerformed
        //Remover Icone do JInternalFrame.
        Container pane = ((BasicInternalFrameUI) janelaConsultar.getUI()).getNorthPane();
        pane.getComponent(0).setVisible(false);
        
        //Adicionando e exibindo a janela "Consultar" centralizada.
        areaTrabalho.add(janelaConsultar);
        janelaConsultar.setVisible(true);
        janelaConsultar.setPosicao();
        janelaConsultar.setRecurso(janelaCadastrar.recursos);
    }//GEN-LAST:event_mnuConsultarActionPerformed

    private void mnuGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGrupoActionPerformed
        //Remover Icone do JInternalFrame.
        Container pane = ((BasicInternalFrameUI) janelaDesenvolvedores.getUI()).getNorthPane();
        pane.getComponent(0).setVisible(false);
        
        //Adicionando e exibindo a janela "Desenvolvedores" centralizada.
        areaTrabalho.remove(janelaConsultar);
        areaTrabalho.remove(janelaCadastrar);
        areaTrabalho.add(janelaDesenvolvedores);
        janelaDesenvolvedores.setVisible(true);
        janelaDesenvolvedores.setPosicao();
    }//GEN-LAST:event_mnuGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuCadastrar;
    private javax.swing.JMenuItem mnuConsultar;
    private javax.swing.JMenuItem mnuGrupo;
    // End of variables declaration//GEN-END:variables
}
